### ISSUE TITLE
Input type on `isValidNumber` incorrect?

### ISSUE THREAD

**Issue by gavinharriscolab** [garganurag893/react-native-phone-number-input#10]
I couldn't get the `isValidNumber` to work on my React Native (TypeScript) project. 

TypeScript really wanted me to pass in a Number Typed value; so I tried:

    const [mobileNumberValue, setMobileNumberValue] = useState('');
    ...
    phoneInput.current?.isValidNumber(Number.parseInt(mobileNumberValue, 10));

However this didn't work (never was valid). So I tried:

    const [mobileNumberValue, setMobileNumberValue] = useState('');
    ...
    // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
    // @ts-ignore
    phoneInput.current?.isValidNumber(mobileNumberValue),

And all appears well (this is forcing the String to be passing in to the function.

**Comment by garganurag893** [comment]
Kindly check v1.1.0

**Comment by gavinharriscolab** [comment]
Confirmed TS is happy now! Thank you!
