### ISSUE TITLE
`defaultValue` is controlled

### ISSUE THREAD

**Issue by petr166** [garganurag893/react-native-phone-number-input#12]
First, thanks for the lib 🙏.

`defaultValue` prop is controlled and reflects `value` state. I need to update `defaultValue` for the input to work.

Proposed solution:
There should be 2 separate props, `defaultValue` for an initial value, and `value` with current functionality of `defaultValue`. What do you think?

**Comment by msheraz007** [comment]
yes I also  facing same issue regarding default value,,

**Comment by garganurag893** [comment]
This issue is fixed. Kindly check v1.2.0

**Comment by v4dkou** [comment]
@garganurag893 There seems to be a regression: in v2.1.0 setting the `value` prop doesn't control the input. 

Somebody made a pull request to fix this:
https://github.com/garganurag893/react-native-phone-number-input/pull/54

Would you kindly accept it?
