### ISSUE TITLE
[Feature] Add a prop to Eliminate Zero After Country Code

### ISSUE THREAD

**Issue by TheSolly** [garganurag893/react-native-phone-number-input#13]
For example; 
Country code +20 and user type the number like 01234567899, formated Number result in +2001234567899 with extra 0 after +20.

For refernce;
https://github.com/thegamenicorus/react-native-phone-input/blob/43d935639a7806b25a9fef15be6c9f6fcd8c88b4/lib/index.js#L166

**Comment by garganurag893** [comment]
Kindly check **getNumberAfterPossiblyEliminatingZero** in v1.2.0. For detailed information, kindly refer to Readme.md
