### ISSUE TITLE
getCountryCode() issue

### ISSUE THREAD

**Issue by ashton-hoss** [garganurag893/react-native-phone-number-input#14]
Thanks for creating this! This was very needed and much better than the existing one!
There is a minor issue. If the user changes the country after entering the phone number, it does not update the country code.
In the example below I entered a US phone number first and then change the country to India. 
As you can see the number starts with +91 but the country is still US.

![image](https://user-images.githubusercontent.com/62814312/96311266-b6d4a180-0fce-11eb-9dae-6ea2900a27ae.png)
![image](https://user-images.githubusercontent.com/62814312/96311415-06b36880-0fcf-11eb-9ca8-0e02c40c3b97.png)
![image](https://user-images.githubusercontent.com/62814312/96311531-48441380-0fcf-11eb-81dc-7f1275d05f77.png)

**Comment by ashton-hoss** [comment]
also is it possible to change the flag size?

**Comment by garganurag893** [comment]
This issue is fixed. Kindly check **v1.2.0**
