### ISSUE TITLE
[FEATURE] expose countryPickerProps in PhoneInput props

### ISSUE THREAD

**Issue by yichengq** [garganurag893/react-native-phone-number-input#16]
Thanks for the lib!

This can enable to configure the country picker component, e.g. I would like to add alpha filter to the country picker page.

**Comment by mouhsnimohamed** [comment]
I think it doesn't support this feature unfortunately

**Comment by garganurag893** [comment]
Thanks for reporting this. It's already present in the code. 
I have updated Readme file for future.
`countryPickerProps={{withAlphaFilter:true}}`
