### ISSUE TITLE
Cannot change placeholder of country list

### ISSUE THREAD

**Issue by ElGecko76** [garganurag893/react-native-phone-number-input#18]
Hello,

I would like to change the placeholder of country list: 

> Enter country name

But I think it is not possible. Can you add this possibility please?

**Comment by garganurag893** [comment]
Thanks for reporting this.
I have added **filterProps** for the same. Kindly check.

Way to use :-
`filterProps={{placeholder:"Enter your placeholder"}}`

**Comment by ElGecko76** [comment]
Thank you very much :)

**Comment by manjusha8** [comment]
Hello,

Unable to change the styling for the placeholder. Wanted to change the default gray color to a different color, but unable to achieve it

Thanks

**Comment by guaba-admin** [comment]
Is it possible to have a style property for the font or each country item?
