### ISSUE TITLE
Preferred countries

### ISSUE THREAD

**Issue by emilyDZC** [garganurag893/react-native-phone-number-input#27]
Thank you for this very useful library. I notice that [react-native-country-picker-modal](https://github.com/xcarpentier/react-native-country-picker-modal) has a `preferredCountries` prop - is there a way to access that here? Or if not, is there another way to limit the countries that are shown in the dropdown?

**Comment by garganurag893** [comment]
Yes, Kindly use the `countryPickerProps` prop.
