### ISSUE TITLE
Prop for country pickup Modal

### ISSUE THREAD

**Issue by imrishabh18** [garganurag893/react-native-phone-number-input#33]
Is there a prop for styling the country pickup modal?

**Comment by garganurag893** [comment]
Yes `countryPickerProps`

**Comment by imrishabh18** [comment]
@garganurag893 But that is not letting me style the countrypicker appearance

**Comment by EliotRaven** [comment]
@garganurag893 could you share all countryPickerProps? Or add this on doc?
