### ISSUE TITLE
How to reduce height of PhoneInput [Android]

### ISSUE THREAD

**Issue by VikasSahu** [garganurag893/react-native-phone-number-input#36]
I want to reduce the size of PhoneInput view, I tried it by providing height in containerStyle, also tried by providing height to parent view. When I give heigh the text is not showing which I am typing. It's working fine in ios.

Please help me out, thanks in advance.

React Native version: [0.63.3]
Platform(s) (iOS, Android, web, or all?): [Android]

**Comment by dtnode** [comment]
set this prop to PhoneInput; **textContainerStyle={{paddingVertical: 0}}**

**Comment by garganurag893** [comment]
textContainerStyle={{paddingVertical: 0}}
