### ISSUE TITLE
Nice component, but useless

### ISSUE THREAD

**Issue by alimoli** [garganurag893/react-native-phone-number-input#47]
Thank you for the library.
I am trying to integrate your component, but it seems very limited for the following reason.

It is not possible to "paste" an international value and get the updated states (country and number without the international prefix).
For this reason, this input is useful only if you don't have a previous value (like a registration form).
But if you want to edit an existing value, this component cannot handle this case.

### Possible solution
I may try to find another library or create my own script to split the country-code prefix from the number, but this attempt cannot be done since the phone input wraps the picker without the possibility to access the state and update that. 

However, I think this is the correct behavior since the developer should not care about the country, but only about the mobile value. If the value contains a prefix, this component should recognize the country code and the number updating the states automatically.

**Comment by morgane1806** [comment]
Did you find a solution ? 

I have a defaultCode="FR"
But when I set a defaultValue or value "+441234567890", the country flag and code don't update
`<PhoneInput
        defaultCode="FR"
        defaultValue="+441234567890"`
<img width="310" alt="Capture d’écran 2021-08-16 à 12 30 23" src="https://user-images.githubusercontent.com/16868491/129550256-2d6b373f-f236-4e53-9725-97be9c1fe798.png">
Do you have a solution in that case ?

**Comment by alimoli** [comment]
@morgane1806 No, I decided to manage it without external libraries since this does not work.

**Comment by davidaik** [comment]
I handled this using the `google-libphonenumber` package.

    const phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();

    const number = phoneUtil.parse(value);
    const countryCode = `+${number.getCountryCode()}`;
    const phoneNumber = value.substring(countryCode.length);
    const regionCode = phoneUtil.getRegionCodeForNumber(number);

I split the phone number, say `+11234567890` into `+1` and `1234567890`. I then pass only `1234567890` to the component, along with the `regionCode` which in this case is `US`.

    <PhoneInput
          defaultValue={phoneNumber}
          value={phoneNumber}
          defaultCode={regionCode}
          layout="first"
          onChangeText={text => {}}
          onChangeFormattedText={text => {}}
        />
