### ISSUE TITLE
Ability to call focus function on text input

### ISSUE THREAD

**Issue by habiiev** [garganurag893/react-native-phone-number-input#48]
Hello! It would be great if you could add the ability to call focus method on text input.
I could create a PR if this is something you would agree on.

**Comment by garganurag893** [comment]
Hi,
You can do that by using **textInputProps** :
`textInputProps={{onFocus: () => {}}}`

**Comment by habiiev** [comment]
No, that's not what I meant.
I need to be able to call `.focus()` method on the text input ref - https://reactnative.dev/docs/textinput#focus.
At this moment I cannot pass in the ref directly to the text input and do that, and ref API for your component does not allow it.
Any chance of adding this?

**Comment by salmanm** [comment]
Yep, the types for `textInputProps` need to be fixed. I'm currently doing this as a workaround

```jsx
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore
          textInputProps={{ ref: mobileRef }}
```

**Comment by Edmund1645** [comment]
Hey @salmanm thanks for this solution, but when I tried to call the `.focus()` method for the text input, it didn't work. Turns out it's actually `null`. Don't know if there's another way I could go about it.

```ts
  const phoneNumberText = useRef<TextInput>(null);

  const focusOnPhoneNumber = () => {
    console.log(phoneNumberText.current); // null
    phoneNumberText.current?.focus(); // not working
    };
    
    // with the component
    
            textInputProps={{
                placeholder: '0434688292',
                keyboardType: 'phone-pad',
                // @ts-ignore
                ref: {phoneNumberText},
              }}


```

**Comment by habiiev** [comment]
> Hey @salmanm thanks for this solution, but when I tried to call the `.focus()` method for the text input, it didn't work. Turns out it's actually `null`. Don't know if there's another way I could go about it.
> 
> 
> 
> ```ts
> 
>   const phoneNumberText = useRef<TextInput>(null);
> 
> 
> 
>   const focusOnPhoneNumber = () => {
> 
>     console.log(phoneNumberText.current); // null
> 
>     phoneNumberText.current?.focus(); // not working
> 
>     };
> 
>     
> 
>     // with the component
> 
>     
> 
>             textInputProps={{
> 
>                 placeholder: '0434688292',
> 
>                 keyboardType: 'phone-pad',
> 
>                 // @ts-ignore
> 
>                 ref: {phoneNumberText},
> 
>               }}
> 
> 
> 
> 
> 
> ```

Hey, I know it's a late reply, but you don't need braces around phoneNumberText

`ref: phoneNumberText`

**Comment by Edmund1645** [comment]
Ohhh right. Thanks!
