### ISSUE TITLE
Disabled does not update with state prop

### ISSUE THREAD

**Issue by KevinVladG** [garganurag893/react-native-phone-number-input#6]
I have a variable prop set to the phone input component for the disabled property. however, when loading the render of my screen the value for disabled is supposed to disable it. This doesn't happen however, I can still interact with it. The only way to disable it is to select a new country to add something to the input field. If you could guide me on how to disable and enable it using my variable that would be great!

**Comment by garganurag893** [comment]
Kindly check the example folder, I have added the use for disable.
