### ISSUE TITLE
How to disable only the modal?

### ISSUE THREAD

**Issue by Eliajn** [garganurag893/react-native-phone-number-input#92]
I want to disable the modal is some cases, is there an option to do that?

**Comment by pierroo** [comment]
if by "modal" you mean the country picker; I am also needing the same feature.
Did you get an answer since? :)

**Comment by garganurag893** [comment]
Hi, You can use this prop for the same `countryPickerProps={{disableNativeModal: true}}`

**Comment by usamaabutt** [comment]
Thanks @garganurag893 it works!!!

**Comment by manojkumarboppisetti** [comment]
It works fine when we pass true, but when it is made conditional using state variable and disables modal is occupying entire area of screen any resolution for this ?
